name: Java CD with Gradle

on:
  push:
    branches: [ "fix/#33/deploy-unupdate-error" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: application.yml 생성
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.PROPERTIES }}" > ./application.yml
        shell: bash

      - name: GOOGLE_APPLICATION_CREDENTIALS_JSON 파일 생성 및 환경변수 설정
        run: |
          mkdir -p ~/credentials
          echo "${{ secrets.GOOGLE_CREDENTIAL_JSON }}" > ~/credentials/google-credentials.json
          echo "GOOGLE_APPLICATION_CREDENTIALS=~/credentials/google-credentials.json" >> $GITHUB_ENV
        shell: bash

      - name: 빌드 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 jar 파일 제작
        run: |
          chmod +x gradlew 
          ./gradlew bootJar

      - name: 웹 이미지 빌드 및 도커허브에 push
        run: |
          TAG=$(date +'%Y%m%d%H%M%S') 
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Docker 컨테이너 배포 및 업데이트
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            TAG=$(date +'%Y%m%d%H%M%S') 
            docker ps -aq | xargs -r docker rm -f
            docker image prune -af
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}:${TAG}
            docker-compose up -d --force-recreate --no-deps --pull always
            sudo docker image prune -f
