name: Java CD with Gradle

on:
  push:
    branches: [ "fix/#33/deploy-unupdate-error" ]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 체크아웃
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'corretto'

      - name: application.yml 생성
        run: |
          cd ./src/main/resources
          touch ./application.yml
          echo "${{ secrets.PROPERTIES }}" > ./application.yml
        shell: bash

      - name: AWS CLI 설치
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install
        shell: bash

      - name: AWS S3에서 GOOGLE_APPLICATION_CREDENTIALS_JSON 파일 다운로드
        run: |
          aws s3 cp s3://${{ secrets.S3_BUCKET_NAME }}/google-credentials.json ./src/main/resources/google-credentials.json
        shell: bash

      - name: GOOGLE_APPLICATION_CREDENTIALS_JSON 검증
        run: |
          cat ./src/main/resources/google-credentials.json | jq '.' > /dev/null || (echo "Invalid JSON file" && exit 1)
        shell: bash

      - name: 빌드 권한 부여
        run: chmod +x gradlew

      - name: 프로젝트 jar 파일 제작
        run: |
          chmod +x gradlew 
          ./gradlew bootJar

      - name: 웹 이미지 빌드 및 도커허브에 push
        run: |
          docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}
          docker build -t ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }} . 
          docker push ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}

      - name: Docker 컨테이너 배포 및 업데이트
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.HOST }}
          username: ubuntu
          key: ${{ secrets.KEY }}
          script: |
            # GOOGLE_APPLICATION_CREDENTIALS 환경 변수 설정
            echo "${{ secrets.GOOGLE_APPLICATION_CREDENTIALS_JSON }}" > /home/ubuntu/google-credentials.json

            # 환경 변수로 설정
            export GOOGLE_APPLICATION_CREDENTIALS="/home/ubuntu/google-credentials.json"

            # 컨테이너 배포 및 업데이트
            sudo docker ps -qa | grep -q . && sudo docker rm -f $(docker ps -qa)
            sudo docker pull ${{ secrets.DOCKER_USERNAME }}/${{ secrets.DOCKER_REPO }}
            docker-compose up -d --force-recreate --no-deps
            sudo docker image prune -f
